---
title: "COPUS"
author: "Stephan Koenig"
format:
  html:
    highlight-style: ayu
    theme:
      light: flatly
      dark: darkly
    embed-resources: true
    citations-hover: true

bibliography: references.bib
csl: ieee.csl

editor_options:
  markdown:
    wrap: sentence
---

## Classroom Observation Protocol for Undergraduate STEM (COPUS)

Classroom Observation Protocol for Undergraduate STEM (COPUS) captures the activities of instructors and students during a class [@smith2013].
The protocol strictly quantifies the time spent on these activities and not the quality of instruction.

```{r}
#| label: setup
#| echo: false
#| message: false

library(conflicted)
library(here)

source(here("R", "functions.R"))
copus_dir <- here("data", "raw")
codes_path <- here("data", "codes.csv")

copus <- process_copus(copus_dir, codes_path)
```

### Data

```{r}
#| label: fig-codes-plots
#| echo: false
#| message: false
#| fig-cap: "Original COPUS codes"
#| fig-subcap:
#|   - "Profile"
#|   - "Timeline"
#| layout-ncol: 2

plot_codes_bars(copus)
plot_codes_timelines(copus)
```

```{r}
#| label: fig-collapsed-codes-plots
#| echo: false
#| message: false
#| fig-cap: "Collapsed COPUS codes [@smith2014]"
#| fig-subcap:
#|   - "Profile"
#|   - "Timeline"
#| layout-ncol: 2

plot_collapsed_codes_bars(copus)
plot_collapsed_codes_timelines(copus)
```
